### ISSUE TITLE
Bug in the delay display.

### ISSUE THREAD

**Issue by jwnhy** [YoungWilliamZ/SUSTC-Qiangke#2]
It's unlikely you will get two identical value from the `random.random()`. ...XD

**Comment by YoungWilliamZ** [comment]
The aim of random is to make the time between two operations different and I think it may act like as a human with super fast response.

**Comment by whexy** [comment]
显示的delay和实际的delay是不同的。

**Comment by YoungWilliamZ** [comment]
> 显示的delay和实际的delay是不同的。

The the true delay = Shown Delay (`random.random()`)  + Runtime of code

When the code runs, you need to wait `random.random()` second, then print the delay (`random.random()`), and there are something else to operation, which will take some times. If your network is slow, it may take more time.

**Comment by whexy** [comment]
how? I don't get it. 
Here's the code.

> delay = random.random()*random.random()
    print(result + "\n正在继续加油!\n············%f s 后" % delay)
    time.sleep(random.random()*random.random())

The program generate a number (say, 0.032), and you print it in the Console.
And, you generate another number (say, 0.7321), and delay it.
So I'm waiting for 0.032sec as you put it in the Console but what I really do is waiting for 0.7321sec.
The right code might be

> time.sleep(delay)

**Comment by jwnhy** [comment]
> how? I don't get it.
> Here's the code.
> 
> > delay = random.random()*random.random()
> > print(result + "\n正在继续加油!\n············%f s 后" % delay)
> > time.sleep(random.random()*random.random())
> 
> The program generate a number (say, 0.032), and you print it in the Console.
> And, you generate another number (say, 0.7321), and delay it.
> So I'm waiting for 0.032sec as you put it in the Console but what I really do is waiting for 0.7321sec.
> The right code might be
> 
> > time.sleep(delay)

I think you're correct and this is what I meant, it's unlikely that Python is so slow that the runtime will influence the error between the two ramdom*ramdom calls.

**Comment by YoungWilliamZ** [comment]
Ok, you are right. 
I have fixed it.
Thank you all to report this.
